spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/football_system_db
    username: root
    password: Eitan1121
  jpa:
    hibernate:
      ddl-auto: update
      generate-ddl: true
      show-sql: true
server:
  port: 80